server:
  port: 13000
#  servlet:
#    path: "*.html"

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///test?characterEncoding=utf8&amp;useSSL=false&amp;serverTimezone=UTC&amp;rewriteBatchedStatements=true
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 0
    password:
    port: 6379

mybatis:
  type-aliases-package: com.forum.pojo
  mapper-locations: classpath:mapper/*.xml
